### ISSUE TITLE
Black-box Testing

### ISSUE THREAD

**Issue by imsmoothlikebutter** [imsmoothlikebutter/ICT2101-2201-Team-Project#35]
State Diagram Link: https://drive.google.com/file/d/1DlkdR6UiSj3q28Im_DuHLRyYmcJyS-8D/view?usp=sharing

**Comment by lhs64** [comment]
### Identify Use cases for the state diagram

There are 10 use cases:

Use case 1: IT Admin adds new site to the system

Use case 2: IT Admin adds new staff to the system

Use case 3: IT Admin adds new manager to the system

Use case 4: Manager assigns work schedule to the Staff

Use case 5: Staff rejects the job that is assigned to him/her

Use case 6: Manager views the schedule of staff

Use case 7: Staff views his/her own job schedule

Use case 8: Staff indicates his/her available dates

Use case 9: Manager views the work hours of the staff

Use case 10: Manager assigns standby personnel to the shift.

The use cases which covers the entire system are **Use Case 4,5,8.**

**Comment by lhs64** [comment]
### Constructing State Diagram
https://app.diagrams.net/#G1DlkdR6UiSj3q28Im_DuHLRyYmcJyS-8D

These are the registered states in the sites. 

1. Login
2. Identify User
3. Seperate into Manager and Staff Views
4. Staff Views Schedule, splits into use case 5 and 8
5. Use case 5: Reject job state, Confirmed Rejection, Inform Manager
6. Use case 8: State Availability, Confirmed Preference, Inform Manager
8. Use case 4: Assign Job, Job Confirmed, Inform Staff

**Comment by lhs64** [comment]
Based on the 10 use cases, construct Decision Tables, Equivalence Partitioning & Boundary Value Analysis

**Comment by lhs64** [comment]
Use case 1: IT Admin creates new site, which involves string values
Decision Table should include string values

Use case 2: IT Admin creates new staff, which involves string values
Decision Table should include string values

Use case 3: IT Admin creates new manager, which involves string values
Decision Table should include string values

Use case 4: Manager assigns work schedule.
Schedule Variables: Staff Name & Backup Name (String), Status (String), Date (DateTime), Period(String), Site_Name (String)
Tested variables include string and datetime.

Use case 5: Staff rejects the job that is assigned to him/her
Rejection: Details(String), StaffName (String)
Only string variables tested.

Use case 6: Manager views the schedule of staff

Use case 7: Staff views his/her own job schedule

Use case 8: Staff indicates his/her available dates
Availability variables: StaffName(String), Date (Datetime), Period (String)
String variables and datetime variables tested.

Use case 9: Manager views the work hours of the staff

Use case 10: Manager assigns standby personnel to the shift.
